export const browserCoreExamples = [
  "brainyx browser status",
  "brainyx browser start",
  "brainyx browser stop",
  "brainyx browser tabs",
  "brainyx browser open https://example.com",
  "brainyx browser focus abcd1234",
  "brainyx browser close abcd1234",
  "brainyx browser screenshot",
  "brainyx browser screenshot --full-page",
  "brainyx browser screenshot --ref 12",
  "brainyx browser snapshot",
  "brainyx browser snapshot --format aria --limit 200",
  "brainyx browser snapshot --efficient",
  "brainyx browser snapshot --labels",
];

export const browserActionExamples = [
  "brainyx browser navigate https://example.com",
  "brainyx browser resize 1280 720",
  "brainyx browser click 12 --double",
  'brainyx browser type 23 "hello" --submit',
  "brainyx browser press Enter",
  "brainyx browser hover 44",
  "brainyx browser drag 10 11",
  "brainyx browser select 9 OptionA OptionB",
  "brainyx browser upload /tmp/file.pdf",
  'brainyx browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "brainyx browser dialog --accept",
  'brainyx browser wait --text "Done"',
  "brainyx browser evaluate --fn '(el) => el.textContent' --ref 7",
  "brainyx browser console --level error",
  "brainyx browser pdf",
];
